export const allStops = [ 
'Go' , 
'Mediterranean' , 
'Chest' , 
'Baltic Avenue' , 
'Income Tax' , 
'Reading Railroad' , 
'Oriental Avenue' , 
'Chance' , 
'Vermont Avenue' , 
'Connecticut' , 
'Just visiting' , 
'St. Charles Place' , 
'Electricity Company' , 
'States Avenue' , 
'Virginia Avenue' , 
'Pennsylvania Railroad' , 
'St. James Place' , 
'Community ' , 
'Tennessee' , 
'New York' , 
'Free Parking' , 
'Kentucky Avenue' , 
'Chance' , 
'Indiana Avenue' , 
'Illinois Avenue' , 
'B&Q Railroad' , 
'Atlantic Avenue' , 
'Ventnor Avenue ' , 
'Water Works' , 
'Marvin Avenue' , 
'GO TO JAIL' , 
'Pacific Avenue' , 
'North Carolina' , 
'Chest' , 
'Pennsylvania Avenue' , 
'Short Line Railroad' , 
'Chance' , 
'Park Place' , 
'TAX PAY 100' , 
'Boardwalk' , 
]