export const db = [ 
  { 
    Name: 'Go', 
    Price: '', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 0, 
  }, 
  { 
    Name: 'Mediterranean', 
    Price: '60', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 0, 
  }, 
  { 
    Name: 'Chest', 
    Price: '', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 0, 
  }, 
  { 
    Name: 'Baltic Avenue', 
    Price: '60', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 0, 
  }, 
  { 
    Name: 'Income Tax', 
    Price: '-200', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 0, 
  }, 
  { 
    Name: 'Reading Railroad', 
    Price: '200', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 0, 
  }, 
  { 
    Name: 'Oriental Avenue', 
    Price: '100', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 0, 
  }, 
  { 
    Name: 'Chance', 
    Price: '', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 0, 
  }, 
  { 
    Name: 'Vermont Avenue', 
    Price: '100', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 0, 
  }, 
  { 
    Name: 'Connecticut', 
    Price: '120', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 0, 
  }, 
  { 
    Name: 'Just visiting', 
    Price: '', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 90, 
  }, 
  { 
    Name: 'St. Charles Place', 
    Price: '140', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 90, 
  }, 
  { 
    Name: 'Electricity Company', 
    Price: '150', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 90, 
  }, 
  { 
    Name: 'States Avenue', 
    Price: '140', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 90, 
  }, 
  { 
    Name: 'Virginia Avenue', 
    Price: '160', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 90, 
  }, 
  { 
    Name: 'Pennsylvania Railroad', 
    Price: '200', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 90, 
  }, 
  { 
    Name: 'St. James Place', 
    Price: '180', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 90, 
  }, 
  { 
    Name: 'Community ', 
    Price: '', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 90, 
  }, 
  { 
    Name: 'Tennessee', 
    Price: '180', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 90, 
  }, 
  { 
    Name: 'New York', 
    Price: '200', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 90, 
  }, 
  { 
    Name: 'Free Parking', 
    Price: '', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 180, 
  }, 
  { 
    Name: 'Kentucky Avenue', 
    Price: '220', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 180, 
  }, 
  { 
    Name: 'Chance', 
    Price: '', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 180, 
  }, 
  { 
    Name: 'Indiana Avenue', 
    Price: '220', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 180, 
  }, 
  { 
    Name: 'Illinois Avenue', 
    Price: '240', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 180, 
  }, 
  { 
    Name: 'B&Q Railroad', 
    Price: '200', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 180, 
  }, 
  { 
    Name: 'Atlantic Avenue', 
    Price: '260', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 180, 
  }, 
  { 
    Name: 'Ventnor Avenue ', 
    Price: '260', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 180, 
  }, 
  { 
    Name: 'Water Works', 
    Price: '150', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 180, 
  }, 
  { 
    Name: 'Marvin Avenue', 
    Price: '280', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 180, 
  }, 
  { 
    Name: 'GO TO JAIL', 
    Price: '', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 270, 
  }, 
  { 
    Name: 'Pacific Avenue', 
    Price: '300', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 270, 
  }, 
  { 
    Name: 'North Carolina', 
    Price: '300', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 270, 
  }, 
  { 
    Name: 'Chest', 
    Price: '', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 270, 
  }, 
  { 
    Name: 'Pennsylvania Avenue', 
    Price: '320', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 270, 
  }, 
  { 
    Name: 'Short Line Railroad', 
    Price: '200', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 270, 
  }, 
  { 
    Name: 'Chance', 
    Price: '', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 270, 
  }, 
  { 
    Name: 'Park Place', 
    Price: '350', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 270, 
  }, 
  { 
    Name: 'TAX PAY 100', 
    Price: '-100', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 270, 
  }, 
  { 
    Name: 'Boardwalk', 
    Price: '400', 
    Property: [{ value: 'Hotel' }], 
    Visiters: [''], 
    Owner: { name: '', color: '' }, 
    deg : 270, 
  }, 
]