export const db = { 
     'Go ': { 
      Name: 'Go', 
      Price: '', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Mediterranean ': { 
      Name: 'Mediterranean', 
      Price: '60', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Chest ': { 
      Name: 'Chest', 
      Price: '', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Baltic Avenue ': { 
      Name: 'Baltic Avenue', 
      Price: '60', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Income Tax ': { 
      Name: 'Income Tax', 
      Price: '-200', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Reading Railroad ': { 
      Name: 'Reading Railroad', 
      Price: '200', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Oriental Avenue ': { 
      Name: 'Oriental Avenue', 
      Price: '100', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Chance ': { 
      Name: 'Chance', 
      Price: '', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Vermont Avenue ': { 
      Name: 'Vermont Avenue', 
      Price: '100', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Connecticut ': { 
      Name: 'Connecticut', 
      Price: '120', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Just visiting ': { 
      Name: 'Just visiting', 
      Price: '', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'St. Charles Place ': { 
      Name: 'St. Charles Place', 
      Price: '140', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Electricity Company ': { 
      Name: 'Electricity Company', 
      Price: '150', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'States Avenue ': { 
      Name: 'States Avenue', 
      Price: '140', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Virginia Avenue ': { 
      Name: 'Virginia Avenue', 
      Price: '160', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Pennsylvania Railroad ': { 
      Name: 'Pennsylvania Railroad', 
      Price: '200', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'St. James Place ': { 
      Name: 'St. James Place', 
      Price: '180', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Community  ': { 
      Name: 'Community ', 
      Price: '', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Tennessee ': { 
      Name: 'Tennessee', 
      Price: '180', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'New York ': { 
      Name: 'New York', 
      Price: '200', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Free Parking ': { 
      Name: 'Free Parking', 
      Price: '', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Kentucky Avenue ': { 
      Name: 'Kentucky Avenue', 
      Price: '220', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Chance ': { 
      Name: 'Chance', 
      Price: '', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Indiana Avenue ': { 
      Name: 'Indiana Avenue', 
      Price: '220', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Illinois Avenue ': { 
      Name: 'Illinois Avenue', 
      Price: '240', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'B&Q Railroad ': { 
      Name: 'B&Q Railroad', 
      Price: '200', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Atlantic Avenue ': { 
      Name: 'Atlantic Avenue', 
      Price: '260', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Ventnor Avenue  ': { 
      Name: 'Ventnor Avenue ', 
      Price: '260', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Water Works ': { 
      Name: 'Water Works', 
      Price: '150', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Marvin Avenue ': { 
      Name: 'Marvin Avenue', 
      Price: '280', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'GO TO JAIL ': { 
      Name: 'GO TO JAIL', 
      Price: '', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Pacific Avenue ': { 
      Name: 'Pacific Avenue', 
      Price: '300', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'North Carolina ': { 
      Name: 'North Carolina', 
      Price: '300', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Chest ': { 
      Name: 'Chest', 
      Price: '', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Pennsylvania Avenue ': { 
      Name: 'Pennsylvania Avenue', 
      Price: '320', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Short Line Railroad ': { 
      Name: 'Short Line Railroad', 
      Price: '200', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Chance ': { 
      Name: 'Chance', 
      Price: '', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Park Place ': { 
      Name: 'Park Place', 
      Price: '350', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'TAX PAY 100 ': { 
      Name: 'TAX PAY 100', 
      Price: '-100', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
     'Boardwalk ': { 
      Name: 'Boardwalk', 
      Price: '400', 
      Property: [{ value: 'Hotel' }], 
      Visiters: [''], 
      Owner: { name: '', color: '' }, 
    }, 
}